[package]
name = "mla"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
cudarc = "0.9.14"
rand = "0.8.5"
round-based = "0.1.7"
